version: "3.8"

services:
  proxy:
    image: jupyterhub/configurable-http-proxy:4
    container_name: proxy
    networks:
      - jupyterhub-network
    ports:
      - "18000:8000"
    restart: unless-stopped
    env_file: .env
    environment:
      - CONFIGPROXY_AUTH_TOKEN=${CONFIGPROXY_AUTH_TOKEN}
    command:
      - configurable-http-proxy
      - "--ip=0.0.0.0"
      - "--port=8000"
      - "--api-ip=0.0.0.0"
      - "--api-port=8001"
      - "--error-target=http://hub:8081/hub/error"
      - "--log-level=info"
      - "--default-target=http://hub:8081"
    depends_on:
      - hub

  hub:
    build:
      context: ./hub/
      dockerfile: Dockerfile
    restart: unless-stopped
    image: danielcristh0/jupyterhub:1.1
    container_name: jupyterhub
    networks:
      - jupyterhub-network
    volumes:
      - "./hub/jupyterhub_config.py:/srv/jupyterhub/jupyterhub_config.py:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/jupyterhub/kernels:/srv/jupyterhub/kernels"
      - "./hub/data:/srv/jupyterhub/data"
    user: root
    command: jupyterhub --config /srv/jupyterhub/jupyterhub_config.py
    expose:
      - "8081"
    env_file: .env
    environment:
      - JUPYTER_GATEWAY_URL=http://jeg:8889
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  jeg:
    build:
      context: ./jeg
      dockerfile: Dockerfile
    restart: unless-stopped
    image: danielcristh0/gateway:1.1
    container_name: jeg
    networks:
      - jupyterhub-network
    ports:
      - "8889:8889"
      - "8877:8877"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/opt/jupyterhub/kernels:/usr/local/share/jupyter/kernels"
      - ./jeg/launch_ipykernel.py:/usr/local/share/jupyter/kernels/python_distributed/scripts/launch_ipykernel.py
      - "./jeg/ssh_keys:/home/jovyan/.ssh:rw"
    depends_on:
      - hub
    env_file: .env
    environment:
      - EG_LOG_LEVEL=${EG_LOG_LEVEL}
      - EG_AUTH_TOKEN=${EG_AUTH_TOKEN}
      - EG_REMOTE_USER=${EG_REMOTE_USER}
      - EG_ALLOW_ORIGIN=*
      - EG_KERNEL_WHITELIST=[]
      - EG_IP=0.0.0.0
      - EG_PORT=8889
      - EG_RESPONSE_IP=${EG_RESPONSE_IP}
      - EG_RESPONSE_PORT=8877
      - EG_RESPONSE_ADDR_ANY=true
      - EG_SOCKET_TIMEOUT=2.0
      - JUPYTER_GATEWAY_HOST=0.0.0.0

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - jupyterhub-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - jupyterhub-network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
    networks:
      - jupyterhub-network

volumes:
  jupyterhub-data:
  grafana_data:
  prometheus_data:

networks:
  jupyterhub-network:
    external: true