version: "3.8"

services:

  ray-worker:
    image: ${RAY_IMAGE}
    depends_on:
      - ray-head
    env_file:
      - .env
    command: bash -c "ray start --address=ray-head:${REDISPORT} --redis-password=${REDISPASSWORD} --num-cpus=${NUM_CPU_WORKER} --block"
    shm_size: 2g
    deploy:
      mode: replicated
      replicas: ${NUM_WORKERS}
      resources:
        limits:
          cpus: 1
          memory: '2g'
    networks:
      - ray_net

networks:
  ray_net:
    driver: bridge