global:
  scrape_interval: 30s
  evaluation_interval: 30s

# rule_files:

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.122.1:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'jupyterhub'
    static_configs:
      - targets: ['192.168.122.1:18000']
    metrics_path: '/hub/metrics'
    scrape_interval: 30s
    authorization:
      type: Bearer
      credentials: monitoring-secret